# Generated by Django 5.2 on 2025-04-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'blog',
                'ordering': ['created'],
            },
        ),
    ]
