# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import saga_pb2 as saga__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in saga_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SagaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSagaTransaction = channel.unary_unary(
                '/SagaService/StartSagaTransaction',
                request_serializer=saga__pb2.StartSagaRequest.SerializeToString,
                response_deserializer=saga__pb2.StartSagaResponse.FromString,
                _registered_method=True)
        self.GetSagaStatusTransaction = channel.unary_unary(
                '/SagaService/GetSagaStatusTransaction',
                request_serializer=saga__pb2.GetSagaStatusRequest.SerializeToString,
                response_deserializer=saga__pb2.GetSagaStatusResponse.FromString,
                _registered_method=True)


class SagaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartSagaTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSagaStatusTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SagaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSagaTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSagaTransaction,
                    request_deserializer=saga__pb2.StartSagaRequest.FromString,
                    response_serializer=saga__pb2.StartSagaResponse.SerializeToString,
            ),
            'GetSagaStatusTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSagaStatusTransaction,
                    request_deserializer=saga__pb2.GetSagaStatusRequest.FromString,
                    response_serializer=saga__pb2.GetSagaStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SagaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SagaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SagaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartSagaTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SagaService/StartSagaTransaction',
            saga__pb2.StartSagaRequest.SerializeToString,
            saga__pb2.StartSagaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSagaStatusTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SagaService/GetSagaStatusTransaction',
            saga__pb2.GetSagaStatusRequest.SerializeToString,
            saga__pb2.GetSagaStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
