# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: saga.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'saga.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsaga.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n\x10StartSagaRequest\x12\x1b\n\x13saga_transaction_id\x18\x01 \x01(\t\x12\x18\n\x05steps\x18\x02 \x03(\x0b\x32\t.SagaStep\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x31\n\x08metadata\x18\x04 \x03(\x0b\x32\x1f.StartSagaRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"j\n\x08SagaStep\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x12\n\nrpc_method\x18\x02 \x01(\t\x12\x1b\n\x13\x63ompensation_method\x18\x03 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x04 \x01(\r\"M\n\x11StartSagaResponse\x12\x1b\n\x13saga_transaction_id\x18\x01 \x01(\t\x12\x1b\n\x06status\x18\x02 \x01(\x0e\x32\x0b.SagaStatus\"3\n\x14GetSagaStatusRequest\x12\x1b\n\x13saga_transaction_id\x18\x01 \x01(\t\"\xde\x01\n\x15GetSagaStatusResponse\x12\x1b\n\x13saga_transaction_id\x18\x01 \x01(\t\x12\x1b\n\x06status\x18\x02 \x01(\x0e\x32\x0b.SagaStatus\x12\x14\n\x0c\x63urrent_step\x18\x03 \x01(\x05\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*h\n\nSagaStatus\x12\x0b\n\x07STARTED\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\x10\n\x0c\x43OMPENSATING\x10\x03\x12\x0f\n\x0b\x43OMPENSATED\x10\x04\x12\n\n\x06\x46\x41ILED\x10\x05\x32\x97\x01\n\x0bSagaService\x12=\n\x14StartSagaTransaction\x12\x11.StartSagaRequest\x1a\x12.StartSagaResponse\x12I\n\x18GetSagaStatusTransaction\x12\x15.GetSagaStatusRequest\x1a\x16.GetSagaStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'saga_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTSAGAREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_STARTSAGAREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SAGASTATUS']._serialized_start=705
  _globals['_SAGASTATUS']._serialized_end=809
  _globals['_STARTSAGAREQUEST']._serialized_start=48
  _globals['_STARTSAGAREQUEST']._serialized_end=238
  _globals['_STARTSAGAREQUEST_METADATAENTRY']._serialized_start=191
  _globals['_STARTSAGAREQUEST_METADATAENTRY']._serialized_end=238
  _globals['_SAGASTEP']._serialized_start=240
  _globals['_SAGASTEP']._serialized_end=346
  _globals['_STARTSAGARESPONSE']._serialized_start=348
  _globals['_STARTSAGARESPONSE']._serialized_end=425
  _globals['_GETSAGASTATUSREQUEST']._serialized_start=427
  _globals['_GETSAGASTATUSREQUEST']._serialized_end=478
  _globals['_GETSAGASTATUSRESPONSE']._serialized_start=481
  _globals['_GETSAGASTATUSRESPONSE']._serialized_end=703
  _globals['_SAGASERVICE']._serialized_start=812
  _globals['_SAGASERVICE']._serialized_end=963
# @@protoc_insertion_point(module_scope)
