# Generated by Django 5.2 on 2025-04-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.IntegerField(),
        ),
    ]
