# Generated by Django 5.2 on 2025-04-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentservice', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
