# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0b\x61uthservice\"D\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"C\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0e\n\x06groups\x18\x04 \x03(\x05\x32\xce\x01\n\x0b\x41uthService\x12G\n\x08Register\x12\x1c.authservice.RegisterRequest\x1a\x1d.authservice.RegisterResponse\x12>\n\x05Login\x12\x19.authservice.LoginRequest\x1a\x1a.authservice.LoginResponse\x12\x36\n\x07GetUser\x12\x18.authservice.UserRequest\x1a\x11.authservice.Userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=27
  _globals['_REGISTERREQUEST']._serialized_end=95
  _globals['_REGISTERRESPONSE']._serialized_start=97
  _globals['_REGISTERRESPONSE']._serialized_end=132
  _globals['_LOGINREQUEST']._serialized_start=134
  _globals['_LOGINREQUEST']._serialized_end=184
  _globals['_LOGINRESPONSE']._serialized_start=186
  _globals['_LOGINRESPONSE']._serialized_end=216
  _globals['_USERREQUEST']._serialized_start=218
  _globals['_USERREQUEST']._serialized_end=243
  _globals['_USER']._serialized_start=245
  _globals['_USER']._serialized_end=312
  _globals['_AUTHSERVICE']._serialized_start=315
  _globals['_AUTHSERVICE']._serialized_end=521
# @@protoc_insertion_point(module_scope)
