# Generated by Django 5.2 on 2025-04-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productservice', '0002_product_created_at_product_description_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_ku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
